name: fliper_teste
description: Projeto de avaliação Fliper

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.2 <3.0.0"

flutter_native_splash:
  image: assets/images/logo_fliper.png
  color: "3B5CB8"
  ios: false

dependencies:
  flutter:
    sdk: flutter

  lib_observer:
    git:
      url: "https://github.com/bicasoftware/lib_observer"

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  dio: ^3.0.10
  http: ^0.12.2
  graphql_flutter: ^3.1.0
  hasura_connect: ^2.0.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_fliper.png

  fonts:
    - family: Proximanova
      fonts:
        - asset: assets/fonts/proxima-nova.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



